version: '3'

services:
  server:
    container_name: message_backend
    image: node:12-alpine
    volumes:
      - ../message-backend/:/src
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on: 
      - db
    command: 'node src/server.js'

  db:
    image: 'mongo'
    container_name: MONGODB_MEDIUM
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  # geocoder:
  #   restart: always
  #   container_name: geocoder
  #   image: python:3
  #   build: ../geocoder
  #   volumes:
  #     - ../geocoder/:/src
  #   ports:
  #     - "5000:5000"
  #   command: 'ls'